import { defineStore } from 'pinia'
import { ref, computed } from 'vue'

export const useLanguageStore = defineStore('language', () => {
  const currentLocale = ref(localStorage.getItem('locale') || 'en')

  const translations = {
    en: {
      // ==================== COMMON ====================
      dashboard: 'Dashboard',
      students: 'Students',
      teachers: 'Teachers',
      classes: 'Classes',
      attendance: 'Attendance',
      payments: 'Payments',
      crm: 'CRM',
      reports: 'Reports',
      parents: 'Parents',
      settings: 'Settings',
      logout: 'Logout',
      login: 'Login',
      register: 'Register',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      add: 'Add',
      search: 'Search',
      filter: 'Filter',
      actions: 'Actions',
      status: 'Status',
      date: 'Date',
      description: 'Description',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      confirm: 'Confirm',
      yes: 'Yes',
      no: 'No',
      back: 'Back',
      next: 'Next',
      previous: 'Previous',
      submit: 'Submit',
      update: 'Update',
      create: 'Create',
      view: 'View',
      total: 'Total',
      active: 'Active',
      inactive: 'Inactive',
      pending: 'Pending',
      approved: 'Approved',
      rejected: 'Rejected',
      cancelled: 'Cancelled',
      select: 'Select',
      refresh: 'Refresh',
      convert: 'Convert',
      processing: 'Processing...',
      submitting: 'Submitting...',
      saveFailed: 'Save failed',
      deleteFailed: 'Delete failed',
      tryAgain: 'Try again',
      noData: 'No data found',
      confirmDelete: 'Are you sure you want to delete this?',
      operationSuccessful: 'Operation completed successfully',
      operationFailed: 'Operation failed',
      networkError: 'Network error. Please check your connection',
      all: 'All',
      searchPlaceholder: 'Search...',
      filterOptions: 'Filter options',
      noResults: 'No results found',

      // ==================== ROLES ====================
      superAdmin: 'Super Admin',
      admin: 'Admin',
      teacher: 'Teacher',
      accountant: 'Accountant',
      parent: 'Parent',
      student: 'Student',
      schoolAdmin: 'School Admin',
      managementPortal: 'Management Portal',

      // ==================== SCHOOL & PUBLIC ====================
      schoolName: 'Zack International Schools and Kindergarten',
      schoolNameShort: 'Zack Schools',
      tagline: 'Where Excellence Meets Values',
      parentPortal: 'Parent Portal',
      accountantPortal: 'Accountant Portal',
      managementPortal: 'Management Portal',
      teacherPortal: 'Teacher Portal',

      // ==================== AUTH & REGISTRATION ====================
      parentRegistration: 'Parent Registration',
      createAccount: 'Create Account',
      confirmPassword: 'Confirm Password',
      passwordsDoNotMatch: 'Passwords do not match',
      passwordTooShort: 'Password must be at least 6 characters',
      passwordRequirements: 'Password must be at least 6 characters',
      alreadyHaveAccount: 'Already have an account?',
      resetPassword: 'Reset Password',
      resetInstructions: 'Enter your email address and we will send you a link to reset your password',
      sendResetLink: 'Send Reset Link',
      backToLogin: 'Back to login',
      resetEmailSent: 'Password reset email sent! Check your inbox.',
      parentRegistrationNote: 'This registration is for parents only. School staff accounts can only be created by the Super Admin.',
      pendingAdminApproval: 'Your account is pending admin approval. You will be notified once approved.',
      registrationFailed: 'Registration failed. Please try again.',
      registrationSuccess: 'Registration successful!',
      pleaseSelectSchool: 'Please select a school',
      welcomeBack: 'Welcome back',
      emailAlreadyRegistered: 'This email is already registered. Please login or use a different email.',
      noSchoolFound: 'No school found. Please contact super admin.',
      parentNotFound: 'Parent profile not found. Please contact school administration.',
      parentNotApproved: 'Your account is not yet approved. Please contact the school administrator.',
      parentNoSchool: 'No school assigned to your account. Please contact the school administrator.',
      pendingApprovalMessage: 'Your account is pending approval from the school administrator. Once approved, you will be able to register children and access all features.',
      contactSchoolAdminForActivation: 'Please contact the school administrator to activate your account.',
      loginFailed: 'Login failed. Please check your credentials.',
      loggingIn: 'Logging in...',
      registering: 'Registering...',
      willNotifyOnApproval: 'You will be notified via email when your account is approved.',
      goToLogin: 'Go to Login',
      goToDashboard: 'Go to Dashboard',
      demoCredentials: 'Demo Credentials',
      editParentDescription: 'Edit parent information',
      addParentDescription: 'Add a new parent',
      editMode: 'Edit Mode',

      // ==================== PARENT DASHBOARD ====================
      parentDashboard: 'Parent Dashboard',
      myChildren: 'My Children',
      registerChild: 'Register Child',
      childRegistrationNote: 'Your child will be registered after admin approval. You will be notified once approved.',
      submitForApproval: 'Submit for Approval',
      childRegistrationSubmitted: 'Child registration submitted for admin approval! You will be notified once approved.',
      awaitingApproval: 'Awaiting Admin Approval',
      noChildren: 'No children found',
      noChildrenFound: 'No children found',
      clickRegisterToAddChild: 'Click "Register Child" to add your first child',
      viewDetails: 'View Details',
      childDetails: 'Child Details',
      childrenAttendance: 'Children Attendance',
      trackYourChildrenAttendance: 'Track your children attendance records',
      manageYourChildren: 'Manage your children and their academic progress',
      registerChildToGetStarted: 'Register a child to get started',

      // ==================== ADMIN DASHBOARD - PENDING APPROVALS ====================
      pendingParentRegistrations: 'Pending Parent Registrations',
      reviewAndApproveParents: 'Review and approve parent registrations',
      approveParentRegistration: 'Approve Parent Registration',
      approveParent: 'Approve Parent',
      approveParentNote: 'This parent will be linked to your school and will be able to register children and view their progress.',
      confirmApproveParent: 'Are you sure you want to approve',
      parentApprovedSuccessfully: 'Parent approved successfully!',
      confirmReject: 'Are you sure you want to reject this parent?',
      relationship: 'Relationship',
      father: 'Father',
      mother: 'Mother',
      guardian: 'Guardian',
      pendingStudentRegistrations: 'Pending Student Registrations',
      reviewStudentRegistrations: 'Review and approve student registrations',
      approveStudentRegistration: 'Approve Student Registration',
      approveAndRegister: 'Approve & Register',
      studentNumberHelp: 'Unique identifier for the student',
      exportReport: 'Export Report',
      thisMonth: 'this month',
      today: 'Today',
      due: 'due',
      activeStaff: 'active staff',
      latestSchoolActivities: 'Latest school activities',
      noRecentActivity: 'No recent activity',
      attendanceTrend: 'Attendance Trend',
      revenueOverview: 'Revenue Overview',
      generateAndExportReports: 'Generate and export reports',
      performanceReportDesc: 'View student performance across subjects',
      attendanceReportDesc: 'View attendance statistics by class',
      revenueReportDesc: 'View revenue and payment statistics',
      pendingPaymentsReportDesc: 'View all pending payments',
      viewAndExportAttendance: 'View and export attendance records',
      tryDifferentFilters: 'Try different filters',
      noAttendanceRecords: 'No attendance records found',

      // ==================== TEACHER MANAGEMENT ====================
      teacherName: 'Teacher Name',
      teacherCode: 'Teacher Code',
      qualification: 'Qualification',
      specialization: 'Specialization',
      hireDate: 'Hire Date',
      onLeave: 'On Leave',
      subjects: 'Subjects',
      notAssigned: 'Not Assigned',
      editTeacher: 'Edit Teacher',
      addTeacher: 'Add Teacher',
      editTeacherDescription: 'Update teacher information and account details',
      addTeacherDescription: 'Create a new teacher account and profile',
      basicInformation: 'Basic Information',
      contactInformation: 'Contact Information',
      professionalInformation: 'Professional Information',
      employmentInformation: 'Employment Information',
      enterFullName: 'Enter full name',
      enterArabicName: 'Enter name in Arabic',
      enterEmail: 'Enter email address',
      enterPhone: 'Enter phone number',
      enterQualification: 'Enter qualification (e.g., Bachelor of Education)',
      enterSpecialization: 'Enter specialization (e.g., Mathematics)',
      enterPassword: 'Enter password',
      teacherAccount: 'Teacher Account',
      teacherAccountHelp: 'Create login credentials for the teacher to access the system',
      saveTeacher: 'Save Teacher',
      accountCredentialsRequired: 'Email and password are required to create a teacher account',
      errorOccurred: 'An error occurred. Please try again.',
      addSubject: 'Add Subject',
      addSubjectPlaceholder: 'Add subject (e.g., Mathematics)',
      noSubjectsAdded: 'No subjects added. Click "Add Subject" to add.',

      // ==================== STUDENT MANAGEMENT ====================
      studentName: 'Student Name',
      studentNumber: 'Student Number',
      dateOfBirth: 'Date of Birth',
      gender: 'Gender',
      male: 'Male',
      female: 'Female',
      enrollmentDate: 'Enrollment Date',
      class: 'Class',
      parent: 'Parent',
      contactInfo: 'Contact Information',
      address: 'Address',
      phone: 'Phone',
      email: 'Email',
      fullName: 'Full Name',
      arabicName: 'Name in Arabic',
      nationality: 'Nationality',
      religion: 'Religion',
      emergencyContact: 'Emergency Contact',
      medicalInfo: 'Medical Information',
      graduated: 'Graduated',
      transferred: 'Transferred',
      suspended: 'Suspended',
      editStudent: 'Edit Student',
      addStudent: 'Add Student',
      studentAccount: 'Student Account',
      studentAccountHelp: 'Create a login account for the student to access the student portal',
      createStudentAccount: 'Create Student Account',
      linkExistingUser: 'Link to existing user',
      createNewAccount: 'Create new account',
      selectUser: 'Select User',
      noAccount: 'No account (student will not have portal access)',
      personalInformation: 'Personal Information',
      academicInformation: 'Academic Information',
      parentInformation: 'Parent Information',
      parentName: 'Parent Name',
      parentPhone: 'Parent Phone',
      manualStudentRequired: 'Please enter at least student name and number',
      studentDetails: 'Student Details',
      studentConvertedSuccessfully: 'Student converted successfully!',
      conversionFailed: 'Conversion failed',
      studentFullName: 'Student Full Name',

      // ==================== CLASS MANAGEMENT ====================
      className: 'Class Name',
      gradeLevel: 'Grade Level',
      section: 'Section',
      academicYear: 'Academic Year',
      capacity: 'Capacity',
      currentEnrollment: 'Current Enrollment',
      selectClass: 'Select Class',
      selectTeacher: 'Select Teacher',
      allClasses: 'All Classes',
      noStudentsInClass: 'No students in this class',
      noClassesAssigned: 'No classes assigned',

      // ==================== ATTENDANCE ====================
      present: 'Present',
      absent: 'Absent',
      late: 'Late',
      excused: 'Excused',
      attendanceReport: 'Attendance Report',
      startDate: 'Start Date',
      endDate: 'End Date',
      generateReport: 'Generate Report',
      attendanceRate: 'Attendance Rate',
      saving: 'Saving...',
      checkIn: 'Check In',
      checkOut: 'Check Out',
      attendanceRecord: 'Attendance Record',
      recentAttendance: 'Recent Attendance',
      noAttendance: 'No attendance records found',
      markedBy: 'Marked By',
      loadStudents: 'Load Students',
      saveAttendance: 'Save Attendance',
      errorSavingAttendance: 'Error saving attendance. Please try again.',
      attendanceSaved: 'Attendance saved successfully!',
      cannotMarkFutureAttendance: 'Cannot mark attendance for future dates',

      // ==================== PAYMENTS ====================
      amount: 'Amount',
      paymentMethod: 'Payment Method',
      bankak: 'Bankak',
      cash: 'Cash',
      dueDate: 'Due Date',
      paymentDate: 'Payment Date',
      transactionId: 'Transaction ID',
      proofImage: 'Proof Image',
      approve: 'Approve',
      reject: 'Reject',
      paymentNumber: 'Payment Number',
      paymentType: 'Payment Type',
      tuition: 'Tuition',
      examFees: 'Exam Fees',
      activityFees: 'Activity Fees',
      other: 'Other',
      bankakNumber: 'Bankak Number',
      currentFile: 'Current file',
      view: 'View',
      paymentApproval: 'Payment Approval',
      noPendingPayments: 'No pending payments',
      addPayment: 'Add Payment',
      selectStudent: 'Select Student',
      reviewAndApprovePayments: 'Review and approve pending payments',
      viewProof: 'View Proof',
      approveError: 'Error approving payment. Please try again.',
      rejectError: 'Error rejecting payment. Please try again.',
      paymentCreatedDate: 'Payment Created Date',
      approvedDate: 'Approved Date',
      whenAdminAddedPayment: 'When admin added the payment',
      whenAccountantApproved: 'When accountant approved',
      notApprovedYet: 'Not approved yet',
      paymentRate: 'Payment Rate',
      paymentDetails: 'Payment Details',
      totalPaid: 'Total Paid',
      pendingAmount: 'Pending Amount',
      totalPayments: 'Total Payments',
      averagePayment: 'Average Payment',
      perTransaction: 'per transaction',
      paymentProof: 'Payment Proof',
      bankakInformation: 'Bankak Information',
      dateInformation: 'Date Information',

      // Payment Form
      selectFromList: 'Select from List',
      manualEntry: 'Manual Entry',
      searchStudentsByNameClassPhone: 'Search students by name, class, or phone...',
      noStudentsFound: 'No students found',
      change: 'Change',
      manualEntryNote: 'Student will be created automatically when you save the payment.',
      schoolInformation: 'School Information',
      school: 'School',
      noSchoolAssigned: 'No school assigned',
      schoolInfoHelp: 'Teachers will be automatically assigned to your school',
      noSchoolAssignedError: 'You are not assigned to any school. Please contact the super administrator.',
      validAmountRequired: 'Please enter a valid amount',
      pleaseSelectStudent: 'Please select a student',
      addPaymentDescription: 'Add a new payment',
      editPaymentDescription: 'Edit payment information',
      createPaymentNote: 'A new payment will be created for the selected student',
      editPaymentNote: 'Edit payment information',
      allPaymentsApproved: 'All payments have been approved',
      confirmApprovePayment: 'Are you sure you want to approve this payment?',
      confirmRejectPayment: 'Are you sure you want to reject this payment?',
      typeToSearchStudents: 'Type to search for a student',
      manualStudentRequired: 'Please enter student name and number',
      totalRevenue: 'Total Revenue',
      revenue: 'Revenue',
      pendingPayments: 'Pending Payments',
      noPaymentsFound: 'No payments found',
      totalPayments: 'Total Payments',
      paymentDetails: 'Payment Details',

      // ==================== SCHOOL BANKAK SETTINGS ====================
      schoolBankakDetails: 'School Bankak Account Details',
      bankakPaymentSettings: 'Bankak Payment Settings',
      bankakSettingsNote: 'Configure your school\'s Bankak account details for parents to see when making payment requests',
      bankakAccountNumber: 'Bankak Account Number',
      enterBankakAccountNumber: 'Enter Bankak account number',
      bankakAccountNumberHelp: 'The school\'s Bankak account number for receiving payments',
      bankakAccountName: 'Account Holder Name',
      enterBankakAccountName: 'Enter account holder name',
      bankakAccountNameHelp: 'The name registered on the Bankak account',
      bankakPhone: 'WhatsApp Number',
      enterBankakPhone: 'Enter WhatsApp number',
      bankakPhoneHelp: 'School WhatsApp number to receive payment notifications',
      bankakReferencePrefix: 'Reference Prefix',
      enterBankakReferencePrefix: 'Enter reference prefix',
      bankakReferenceHelp: 'Prefix used for payment reference (e.g., ZACK)',
      parentViewPreview: 'Parent View Preview',
      reset: 'Reset',
      saveSettings: 'Save Settings',
      settingsSavedSuccessfully: 'Settings saved successfully!',
      errorLoadingSettings: 'Error loading settings',
      errorSavingSettings: 'Error saving settings',
      schoolCode: 'School Code',

      // ==================== PARENT PAYMENT REQUESTS ====================
      trackAndManagePayments: 'Track and manage your payments',
      requestPayment: 'Request Payment',
      submitRequest: 'Submit Request',
      payCashAtSchool: 'Pay cash at the school cashier',
      bankakInstructions: 'Make Bankak transfer using the number above',
      keepReceipt: 'Keep your receipt for reference',
      paymentRequestSubmitted: 'Payment request submitted successfully!',
      pleaseFillRequiredFields: 'Please fill all required fields',
      paymentInstructions: 'Payment Instructions',
      downloadReceipt: 'Download Receipt',
      close: 'Close',
      parentPaymentRequests: 'Parent Payment Requests',
      parentRequests: 'Parent Requests',
      parentRequest: 'Parent Request',
      markReceived: 'Mark as Received',
      confirmMarkReceived: 'Are you sure you want to mark this payment as received?',
      paymentMarkedReceived: 'Payment marked as received!',
      markPaymentReceived: 'Mark Payment as Received',
      bankakAccount: 'Bankak Account',
      thanksForPayment: 'Thank you for your payment',
      paymentNotification: 'Payment Notification',
      whatsappConfirmation: 'WhatsApp Payment Confirmation',
      whatsappConfirmationNote: 'Send payment notification via WhatsApp with the payment receipt screenshot',
      sendWhatsApp: 'Send via WhatsApp',
      copyMessage: 'Copy Message',
      messageCopied: 'Message copied!',
      accountNumber: 'Account Number',
      accountName: 'Account Name',
      reference: 'Reference',
      whenAdminAddedPayment: 'When admin added the payment',
      whenAccountantApproved: 'When accountant approved',
      notApprovedYet: 'Not approved yet',
      paymentCreated: 'Payment Created',
      paymentRate: 'Payment Rate',

      // ==================== TEACHER DASHBOARD & SIDEBAR ====================
      manageYourClasses: 'Manage your classes',
      myClasses: 'My Classes',
      myStudents: 'My Students',
      studentsInYourClasses: 'Students enrolled in your classes',
      filterByClass: 'Filter by Class',
      searchByNameOrNumber: 'Search by name or student number',
      noStudentsFound: 'No students found',
      classesYouTeach: 'Classes you are assigned to teach',
      markAttendance: 'Mark Attendance',
      viewStudents: 'View Students',
      accessDenied: 'Access denied',
      teacherDashboard: 'Teacher Dashboard',
      welcomeBackTeacher: 'Welcome back teacher',
      allClasses: 'All Classes',
      addExam: 'Add Exam',
      recentActivities: 'Recent Activities',
      noRecentActivity: 'No recent activity',
      minutesAgo: 'minutes ago',
      hoursAgo: 'hours ago',
      daysAgo: 'days ago',
      noClassesAssigned: 'No classes assigned to you',
      noClassesFound: 'No classes found',
      examGrades: 'Exam Results',

      // ==================== ADDITIONAL KEYS ====================
      clickRegisterToAddChild: 'Click "Register Child" to add your first child',
      studentId: 'Student ID',
      viewAllLeads: 'View all leads',
      viewAllPending: 'View all pending',
      reviewPayment: 'Review Payment',
      paymentsAwaitingYourApproval: 'Payments awaiting your approval',
      allPaymentsHaveBeenProcessed: 'All payments have been processed',
      reviewAndApprove: 'Review and approve',
      convertAndRegister: 'Convert and Register',
      selectChildToViewAttendance: 'Select a child to view attendance',
      selectChildToViewGrades: 'Select a child to view grades',
      childNotFound: 'Child not found',
      registerChildToGetStarted: 'Register a child to get started',
      upcomingExams: 'Upcoming Exams',
      todayAttendance: 'Today\'s Attendance',

      // Navigation & Footer
      home: 'Home',
      about: 'About',
      programs: 'Programs',
      admissions: 'Admissions',
      contact: 'Contact',
      footerAboutText: 'Providing quality education for future leaders since 2000. We are committed to excellence in teaching and learning.',
      quickLinks: 'Quick Links',
      workingHours: 'Working Hours',
      sundayToThursday: 'Sunday - Thursday',
      friday: 'Friday',
      closed: 'Closed',
      saturday: 'Saturday',
      allRightsReserved: 'All rights reserved',

      // Schedule
      previousWeek: 'Previous Week',
      nextWeek: 'Next Week',
      time: 'Time',
      teacher: 'Teacher',
      room: 'Room',
      legend: 'Legend',
      regularClass: 'Regular Class',
      exam: 'Exam',
      activity: 'Activity',
      holiday: 'Holiday',
      noSchedule: 'No classes scheduled for this day',

      // Dashboard Stats
      totalStudents: 'Total Students',
      totalTeachers: 'Total Teachers',
      pendingParents: 'Pending Parents',
      pendingStudents: 'Pending Students',
      newLeads: 'New Leads',
      conversionRate: 'Conversion Rate',

      // Messages
      confirmDelete: 'Are you sure you want to delete this?',
      operationSuccessful: 'Operation completed successfully',
      operationFailed: 'Operation failed',
      networkError: 'Network error. Please check your connection',
      tryAgain: 'Try again',
      submitting: 'Submitting...'
    },
    ar: {
      // ==================== COMMON ====================
      dashboard: 'لوحة التحكم',
      students: 'الطلاب',
      teachers: 'المعلمين',
      classes: 'الفصول',
      attendance: 'الحضور',
      payments: 'المدفوعات',
      crm: 'إدارة علاقات العملاء',
      reports: 'التقارير',
      parents: 'أولياء الأمور',
      settings: 'الإعدادات',
      logout: 'تسجيل خروج',
      login: 'تسجيل دخول',
      register: 'تسجيل',
      save: 'حفظ',
      cancel: 'إلغاء',
      delete: 'حذف',
      edit: 'تعديل',
      add: 'إضافة',
      search: 'بحث',
      filter: 'تصفية',
      actions: 'إجراءات',
      status: 'الحالة',
      date: 'التاريخ',
      description: 'الوصف',
      loading: 'جاري التحميل...',
      error: 'خطأ',
      success: 'نجاح',
      confirm: 'تأكيد',
      yes: 'نعم',
      no: 'لا',
      back: 'رجوع',
      next: 'التالي',
      previous: 'السابق',
      submit: 'إرسال',
      update: 'تحديث',
      create: 'إنشاء',
      view: 'عرض',
      total: 'الإجمالي',
      active: 'نشط',
      inactive: 'غير نشط',
      pending: 'قيد الانتظار',
      approved: 'موافق',
      rejected: 'مرفوض',
      cancelled: 'ملغي',
      select: 'اختر',
      refresh: 'تحديث',
      convert: 'تحويل',
      processing: 'جاري المعالجة...',
      submitting: 'جاري الإرسال...',
      saveFailed: 'فشل الحفظ',
      deleteFailed: 'فشل الحذف',
      tryAgain: 'حاول مرة أخرى',
      noData: 'لا توجد بيانات',
      confirmDelete: 'هل أنت متأكد من الحذف؟',
      operationSuccessful: 'تمت العملية بنجاح',
      operationFailed: 'فشلت العملية',
      networkError: 'خطأ في الشبكة. يرجى التحقق من الاتصال',
      all: 'الكل',
      searchPlaceholder: 'بحث...',
      filterOptions: 'خيارات التصفية',
      noResults: 'لا توجد نتائج',

      // ==================== ROLES ====================
      superAdmin: 'مشرف عام',
      admin: 'مدير مدرسة',
      teacher: 'معلم',
      accountant: 'محاسب',
      parent: 'ولي أمر',
      student: 'طالب',
      schoolAdmin: 'مدير مدرسة',
      managementPortal: 'بوابة الإدارة',

      // ==================== SCHOOL & PUBLIC ====================
      schoolName: 'رياض ومدارس زاك العالمية',
      schoolNameShort: 'مدارس زاك',
      tagline: 'حيث تلتقي التميز بالقيم',
      parentPortal: 'بوابة ولي الأمر',
      accountantPortal: 'بوابة المحاسب',
      managementPortal: 'بوابة الإدارة',
      teacherPortal: 'بوابة المعلم',

      // ==================== AUTH & REGISTRATION ====================
      parentRegistration: 'تسجيل ولي الأمر',
      createAccount: 'إنشاء حساب',
      confirmPassword: 'تأكيد كلمة المرور',
      passwordsDoNotMatch: 'كلمات المرور غير متطابقة',
      passwordTooShort: 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل',
      passwordRequirements: 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل',
      alreadyHaveAccount: 'لديك حساب بالفعل؟',
      resetPassword: 'إعادة تعيين كلمة المرور',
      resetInstructions: 'أدخل بريدك الإلكتروني وسنرسل لك رابطاً لإعادة تعيين كلمة المرور',
      sendResetLink: 'إرسال رابط إعادة التعيين',
      backToLogin: 'العودة إلى تسجيل الدخول',
      resetEmailSent: 'تم إرسال بريد إعادة تعيين كلمة المرور! تحقق من صندوق الوارد.',
      parentRegistrationNote: 'هذا التسجيل مخصص لأولياء الأمور فقط. يمكن إنشاء حسابات موظفي المدرسة فقط بواسطة المشرف العام.',
      pendingAdminApproval: 'حسابك قيد موافقة المسؤول. سيتم إعلامك عند الموافقة.',
      registrationFailed: 'فشل التسجيل. يرجى المحاولة مرة أخرى.',
      registrationSuccess: 'تم التسجيل بنجاح!',
      pleaseSelectSchool: 'يرجى اختيار المدرسة',
      welcomeBack: 'مرحباً بعودتك',
      emailAlreadyRegistered: 'هذا البريد الإلكتروني مسجل بالفعل. يرجى تسجيل الدخول أو استخدام بريد مختلف.',
      noSchoolFound: 'لم يتم العثور على المدرسة. يرجى الاتصال بالمشرف العام.',
      parentNotFound: 'لم يتم العثور على ملف ولي الأمر. يرجى الاتصال بإدارة المدرسة.',
      parentNotApproved: 'حسابك لم تتم الموافقة عليه بعد. يرجى الاتصال بمسؤول المدرسة.',
      parentNoSchool: 'لا توجد مدرسة مرتبطة بحسابك. يرجى الاتصال بمسؤول المدرسة.',
      pendingApprovalMessage: 'حسابك قيد موافقة مسؤول المدرسة. بمجرد الموافقة، ستتمكن من تسجيل الأطفال والوصول إلى جميع الميزات.',
      contactSchoolAdminForActivation: 'يرجى الاتصال بمسؤول المدرسة لتفعيل حسابك.',
      loginFailed: 'فشل تسجيل الدخول. يرجى التحقق من بيانات الدخول.',
      loggingIn: 'جاري تسجيل الدخول...',
      registering: 'جاري التسجيل...',
      willNotifyOnApproval: 'سيتم إشعارك عبر البريد الإلكتروني عند الموافقة على حسابك.',
      goToLogin: 'الذهاب إلى تسجيل الدخول',
      goToDashboard: 'الذهاب إلى لوحة التحكم',
      demoCredentials: 'بيانات الدخول التجريبية',
      editParentDescription: 'تعديل معلومات ولي الأمر',
      addParentDescription: 'إضافة ولي أمر جديد',
      editMode: 'وضع التعديل',

      // ==================== PARENT DASHBOARD ====================
      parentDashboard: 'لوحة تحكم ولي الأمر',
      myChildren: 'أطفالي',
      registerChild: 'تسجيل طفل',
      childRegistrationNote: 'سيتم تسجيل طفلك بعد موافقة المسؤول. سيتم إعلامك بمجرد الموافقة.',
      submitForApproval: 'إرسال للموافقة',
      childRegistrationSubmitted: 'تم إرسال تسجيل الطفل للموافقة! سيتم إعلامك بمجرد الموافقة.',
      awaitingApproval: 'في انتظار موافقة المسؤول',
      noChildren: 'لا يوجد أطفال',
      noChildrenFound: 'لا يوجد أطفال',
      clickRegisterToAddChild: 'انقر "تسجيل طفل" لإضافة طفلك الأول',
      viewDetails: 'عرض التفاصيل',
      childDetails: 'تفاصيل الطفل',
      childrenAttendance: 'حضور الأطفال',
      trackYourChildrenAttendance: 'تتبع سجلات حضور أطفالك',
      manageYourChildren: 'إدارة أطفالك وتقدمهم الأكاديمي',
      registerChildToGetStarted: 'سجل طفلاً للبدء',

      // ==================== ADMIN DASHBOARD - PENDING APPROVALS ====================
      pendingParentRegistrations: 'تسجيلات أولياء الأمور المعلقة',
      reviewAndApproveParents: 'مراجعة والموافقة على تسجيلات أولياء الأمور',
      approveParentRegistration: 'الموافقة على تسجيل ولي الأمر',
      approveParent: 'الموافقة على ولي الأمر',
      approveParentNote: 'سيتم ربط ولي الأمر بمدرستك وسيتمكن من تسجيل الأطفال ومتابعة تقدمهم.',
      confirmApproveParent: 'هل أنت متأكد من الموافقة على',
      parentApprovedSuccessfully: 'تمت الموافقة على ولي الأمر بنجاح!',
      confirmReject: 'هل أنت متأكد من رفض هذا ولي الأمر؟',
      relationship: 'صلة القرابة',
      father: 'أب',
      mother: 'أم',
      guardian: 'وصي',
      pendingStudentRegistrations: 'تسجيلات الطلاب المعلقة',
      reviewStudentRegistrations: 'مراجعة والموافقة على تسجيلات الطلاب',
      approveStudentRegistration: 'الموافقة على تسجيل الطالب',
      approveAndRegister: 'موافقة وتسجيل',
      studentNumberHelp: 'معرف فريد للطالب',
      exportReport: 'تصدير التقرير',
      thisMonth: 'هذا الشهر',
      today: 'اليوم',
      due: 'مستحق',
      activeStaff: 'موظفين نشطين',
      latestSchoolActivities: 'أحدث الأنشطة المدرسية',
      noRecentActivity: 'لا يوجد نشاط حديث',
      attendanceTrend: 'اتجاه الحضور',
      revenueOverview: 'نظرة عامة على الإيرادات',
      generateAndExportReports: 'إنشاء وتصدير التقارير',
      performanceReportDesc: 'عرض أداء الطلاب في المواد المختلفة',
      attendanceReportDesc: 'عرض إحصائيات الحضور حسب الفصل',
      revenueReportDesc: 'عرض إحصائيات الإيرادات والمدفوعات',
      pendingPaymentsReportDesc: 'عرض جميع المدفوعات المعلقة',
      viewAndExportAttendance: 'عرض وتصدير سجلات الحضور',
      tryDifferentFilters: 'جرب عوامل تصفية مختلفة',
      noAttendanceRecords: 'لا توجد سجلات حضور',

      // ==================== TEACHER MANAGEMENT ====================
      teacherName: 'اسم المعلم',
      teacherCode: 'رمز المعلم',
      qualification: 'المؤهل',
      specialization: 'التخصص',
      hireDate: 'تاريخ التوظيف',
      onLeave: 'في إجازة',
      subjects: 'المواد',
      notAssigned: 'غير معين',
      editTeacher: 'تعديل المعلم',
      addTeacher: 'إضافة معلم',
      editTeacherDescription: 'تحديث معلومات المعلم وتفاصيل الحساب',
      addTeacherDescription: 'إنشاء حساب معلم جديد وملف شخصي',
      basicInformation: 'المعلومات الأساسية',
      contactInformation: 'معلومات الاتصال',
      professionalInformation: 'المعلومات المهنية',
      employmentInformation: 'معلومات التوظيف',
      enterFullName: 'أدخل الاسم الكامل',
      enterArabicName: 'أدخل الاسم بالعربية',
      enterEmail: 'أدخل البريد الإلكتروني',
      enterPhone: 'أدخل رقم الهاتف',
      enterQualification: 'أدخل المؤهل (مثل: بكالوريوس تربية)',
      enterSpecialization: 'أدخل التخصص (مثل: رياضيات)',
      enterPassword: 'أدخل كلمة المرور',
      teacherAccount: 'حساب المعلم',
      teacherAccountHelp: 'إنشاء بيانات تسجيل دخول للمعلم للوصول إلى النظام',
      saveTeacher: 'حفظ المعلم',
      accountCredentialsRequired: 'البريد الإلكتروني وكلمة المرور مطلوبان لإنشاء حساب المعلم',
      errorOccurred: 'حدث خطأ. يرجى المحاولة مرة أخرى.',
      addSubject: 'إضافة مادة',
      addSubjectPlaceholder: 'أضف مادة (مثل: رياضيات)',
      noSubjectsAdded: 'لم يتم إضافة مواد. انقر "إضافة مادة" للإضافة.',

      // ==================== STUDENT MANAGEMENT ====================
      studentName: 'اسم الطالب',
      studentNumber: 'رقم الطالب',
      dateOfBirth: 'تاريخ الميلاد',
      gender: 'الجنس',
      male: 'ذكر',
      female: 'أنثى',
      enrollmentDate: 'تاريخ التسجيل',
      class: 'الفصل',
      parent: 'ولي الأمر',
      contactInfo: 'معلومات الاتصال',
      address: 'العنوان',
      phone: 'الهاتف',
      email: 'البريد الإلكتروني',
      fullName: 'الاسم الكامل',
      arabicName: 'الاسم بالعربية',
      nationality: 'الجنسية',
      religion: 'الديانة',
      emergencyContact: 'جهة اتصال للطوارئ',
      medicalInfo: 'معلومات طبية',
      graduated: 'متخرج',
      transferred: 'منقول',
      suspended: 'موقوف',
      editStudent: 'تعديل الطالب',
      addStudent: 'إضافة طالب',
      studentAccount: 'حساب الطالب',
      studentAccountHelp: 'إنشاء حساب تسجيل دخول للطالب للوصول إلى بوابة الطالب',
      createStudentAccount: 'إنشاء حساب طالب',
      linkExistingUser: 'ربط بمستخدم موجود',
      createNewAccount: 'إنشاء حساب جديد',
      selectUser: 'اختر المستخدم',
      noAccount: 'لا يوجد حساب (لن يكون للطالب وصول إلى البوابة)',
      personalInformation: 'المعلومات الشخصية',
      academicInformation: 'المعلومات الأكاديمية',
      parentInformation: 'معلومات ولي الأمر',
      parentName: 'اسم ولي الأمر',
      parentPhone: 'هاتف ولي الأمر',
      manualStudentRequired: 'يرجى إدخال اسم الطالب ورقمه على الأقل',
      studentDetails: 'تفاصيل الطالب',
      studentConvertedSuccessfully: 'تم تحويل الطالب بنجاح!',
      conversionFailed: 'فشل التحويل',
      studentFullName: 'اسم الطالب الكامل',

      // ==================== CLASS MANAGEMENT ====================
      className: 'اسم الفصل',
      gradeLevel: 'الصف الدراسي',
      section: 'الشعبة',
      academicYear: 'السنة الدراسية',
      capacity: 'السعة',
      currentEnrollment: 'عدد المسجلين',
      selectClass: 'اختر الفصل',
      selectTeacher: 'اختر المعلم',
      allClasses: 'جميع الفصول',
      noStudentsInClass: 'لا يوجد طلاب في هذا الفصل',
      noClassesAssigned: 'لا توجد فصول مخصصة',

      // ==================== ATTENDANCE ====================
      present: 'حاضر',
      absent: 'غائب',
      late: 'متأخر',
      excused: 'معذور',
      attendanceReport: 'تقرير الحضور',
      startDate: 'تاريخ البداية',
      endDate: 'تاريخ النهاية',
      generateReport: 'إنشاء التقرير',
      attendanceRate: 'نسبة الحضور',
      saving: 'جاري الحفظ...',
      checkIn: 'وقت الدخول',
      checkOut: 'وقت الخروج',
      attendanceRecord: 'سجل الحضور',
      recentAttendance: 'الحضور الأخير',
      noAttendance: 'لا توجد سجلات حضور',
      markedBy: 'تم بواسطة',
      loadStudents: 'تحميل الطلاب',
      saveAttendance: 'حفظ الحضور',
      errorSavingAttendance: 'خطأ في حفظ الحضور. يرجى المحاولة مرة أخرى.',
      attendanceSaved: 'تم حفظ الحضور بنجاح!',
      cannotMarkFutureAttendance: 'لا يمكن تسجيل الحضور للتواريخ المستقبلية',

      // ==================== PAYMENTS ====================
      amount: 'المبلغ',
      paymentMethod: 'طريقة الدفع',
      bankak: 'بنكك',
      cash: 'نقدي',
      dueDate: 'تاريخ الاستحقاق',
      paymentDate: 'تاريخ الدفع',
      transactionId: 'رقم المعاملة',
      proofImage: 'صورة الإثبات',
      approve: 'موافقة',
      reject: 'رفض',
      paymentNumber: 'رقم الدفع',
      paymentType: 'نوع الدفع',
      tuition: 'رسوم دراسية',
      examFees: 'رسوم امتحانات',
      activityFees: 'رسوم أنشطة',
      other: 'أخرى',
      bankakNumber: 'رقم بنكك',
      currentFile: 'الملف الحالي',
      view: 'عرض',
      paymentApproval: 'الموافقة على الدفعات',
      noPendingPayments: 'لا توجد دفعات معلقة',
      addPayment: 'إضافة دفعة',
      selectStudent: 'اختر الطالب',
      reviewAndApprovePayments: 'مراجعة والموافقة على المدفوعات المعلقة',
      viewProof: 'عرض الإثبات',
      approveError: 'حدث خطأ أثناء الموافقة على الدفع. يرجى المحاولة مرة أخرى.',
      rejectError: 'حدث خطأ أثناء رفض الدفع. يرجى المحاولة مرة أخرى.',
      paymentCreatedDate: 'تاريخ إنشاء الدفع',
      approvedDate: 'تاريخ الموافقة',
      whenAdminAddedPayment: 'عندما أضاف المسؤول الدفع',
      whenAccountantApproved: 'عندما وافق المحاسب',
      notApprovedYet: 'لم تتم الموافقة بعد',
      paymentRate: 'نسبة الدفع',
      paymentDetails: 'تفاصيل الدفع',
      totalPaid: 'إجمالي المدفوع',
      pendingAmount: 'المبلغ المعلق',
      totalPayments: 'إجمالي المدفوعات',
      averagePayment: 'متوسط الدفع',
      perTransaction: 'لكل معاملة',
      paymentProof: 'إثبات الدفع',
      bankakInformation: 'معلومات بنكك',
      dateInformation: 'معلومات التاريخ',

      // Payment Form
      selectFromList: 'اختر من القائمة',
      manualEntry: 'إدخال يدوي',
      searchStudentsByNameClassPhone: 'بحث عن طالب بالاسم، الفصل، أو الهاتف...',
      noStudentsFound: 'لا يوجد طلاب',
      change: 'تغيير',
      manualEntryNote: 'سيتم إنشاء الطالب تلقائياً عند حفظ الدفعة.',
      schoolInformation: 'معلومات المدرسة',
      school: 'المدرسة',
      noSchoolAssigned: 'لا توجد مدرسة مرتبطة',
      schoolInfoHelp: 'سيتم تعيين المعلمين تلقائيًا إلى مدرستك',
      noSchoolAssignedError: 'أنت غير مرتبط بأي مدرسة. يرجى الاتصال بالمشرف العام.',
      validAmountRequired: 'يرجى إدخال مبلغ صحيح',
      pleaseSelectStudent: 'يرجى اختيار الطالب',
      addPaymentDescription: 'إضافة دفعة جديدة',
      editPaymentDescription: 'تعديل معلومات الدفعة',
      createPaymentNote: 'سيتم إنشاء دفعة جديدة للطالب المحدد',
      editPaymentNote: 'تعديل معلومات الدفعة',
      allPaymentsApproved: 'جميع المدفوعات تمت الموافقة عليها',
      confirmApprovePayment: 'هل أنت متأكد من الموافقة على هذه الدفعة؟',
      confirmRejectPayment: 'هل أنت متأكد من رفض هذه الدفعة؟',
      typeToSearchStudents: 'اكتب للبحث عن طالب',
      manualStudentRequired: 'يرجى إدخال اسم الطالب ورقمه',
      totalRevenue: 'إجمالي الإيرادات',
      revenue: 'الإيرادات',
      pendingPayments: 'المدفوعات المعلقة',
      noPaymentsFound: 'لا يوجد مدفوعات',
      totalPayments: 'إجمالي المدفوعات',
      paymentDetails: 'تفاصيل الدفعة',

      // ==================== SCHOOL BANKAK SETTINGS ====================
      schoolBankakDetails: 'تفاصيل حساب بنكك للمدرسة',
      bankakPaymentSettings: 'إعدادات الدفع عبر بنكك',
      bankakSettingsNote: 'قم بإعداد تفاصيل حساب بنكك الخاصة بالمدرسة لعرضها لأولياء الأمور عند طلب الدفع',
      bankakAccountNumber: 'رقم حساب بنكك',
      enterBankakAccountNumber: 'أدخل رقم حساب بنكك',
      bankakAccountNumberHelp: 'رقم حساب بنكك الخاص بالمدرسة',
      bankakAccountName: 'اسم صاحب الحساب',
      enterBankakAccountName: 'أدخل اسم صاحب الحساب',
      bankakAccountNameHelp: 'الاسم المسجل في حساب بنكك',
      bankakPhone: 'رقم الواتساب',
      enterBankakPhone: 'أدخل رقم الواتساب',
      bankakPhoneHelp: 'رقم واتساب المدرسة لتلقي إشعارات الدفع',
      bankakReferencePrefix: 'بادئة المرجع',
      enterBankakReferencePrefix: 'أدخل بادئة المرجع',
      bankakReferenceHelp: 'بادئة تستخدم في مرجع الدفع (مثال: ZACK)',
      parentViewPreview: 'معاينة عرض ولي الأمر',
      reset: 'إعادة تعيين',
      saveSettings: 'حفظ الإعدادات',
      settingsSavedSuccessfully: 'تم حفظ الإعدادات بنجاح!',
      errorLoadingSettings: 'خطأ في تحميل الإعدادات',
      errorSavingSettings: 'خطأ في حفظ الإعدادات',
      schoolCode: 'رمز المدرسة',

      // ==================== PARENT PAYMENT REQUESTS ====================
      trackAndManagePayments: 'تتبع وإدارة مدفوعاتك',
      requestPayment: 'طلب دفعة',
      submitRequest: 'إرسال الطلب',
      payCashAtSchool: 'الدفع نقداً في خزينة المدرسة',
      bankakInstructions: 'التحويل عبر بنكك باستخدام الرقم أعلاه',
      keepReceipt: 'احتفظ بالإيصال للمراجعة',
      paymentRequestSubmitted: 'تم إرسال طلب الدفع بنجاح!',
      pleaseFillRequiredFields: 'يرجى تعبئة جميع الحقول المطلوبة',
      paymentInstructions: 'تعليمات الدفع',
      downloadReceipt: 'تحميل الإيصال',
      close: 'إغلاق',
      parentPaymentRequests: 'طلبات الدفع من ولي الأمر',
      parentRequests: 'طلبات ولي الأمر',
      parentRequest: 'طلب ولي أمر',
      markReceived: 'تأكيد الاستلام',
      confirmMarkReceived: 'هل أنت متأكد من تأكيد استلام الدفعة؟',
      paymentMarkedReceived: 'تم تأكيد استلام الدفعة!',
      markPaymentReceived: 'تأكيد استلام الدفعة',
      bankakAccount: 'حساب بنكك',
      thanksForPayment: 'شكراً لدفعكم',
      paymentNotification: 'إشعار دفع',
      whatsappConfirmation: 'تأكيد الدفع عبر واتساب',
      whatsappConfirmationNote: 'أرسل إشعار الدفع عبر واتساب مع صورة الإشعار',
      sendWhatsApp: 'إرسال عبر واتساب',
      copyMessage: 'نسخ الرسالة',
      messageCopied: 'تم نسخ الرسالة!',
      accountNumber: 'رقم الحساب',
      accountName: 'اسم الحساب',
      reference: 'المرجع',
      whenAdminAddedPayment: 'عندما أضاف المسؤول الدفع',
      whenAccountantApproved: 'عندما وافق المحاسب',
      notApprovedYet: 'لم تتم الموافقة بعد',
      paymentCreated: 'تم إنشاء الدفع',
      paymentRate: 'نسبة الدفع',

      // ==================== TEACHER DASHBOARD & SIDEBAR ====================
      manageYourClasses: 'إدارة فصولك',
      myClasses: 'فصولي',
      myStudents: 'طلابي',
      studentsInYourClasses: 'الطلاب المسجلون في فصولك',
      filterByClass: 'تصفية حسب الفصل',
      searchByNameOrNumber: 'بحث بالاسم أو رقم الطالب',
      noStudentsFound: 'لا يوجد طلاب',
      classesYouTeach: 'الفصول التي تدرسها',
      markAttendance: 'تسجيل الحضور',
      viewStudents: 'عرض الطلاب',
      accessDenied: 'وصول ممنوع',
      teacherDashboard: 'لوحة تحكم المعلم',
      welcomeBackTeacher: 'مرحباً بك مرة أخرى أيها المعلم',
      allClasses: 'جميع الفصول',
      addExam: 'إضافة اختبار',
      recentActivities: 'الأنشطة الأخيرة',
      noRecentActivity: 'لا توجد أنشطة حديثة',
      minutesAgo: 'دقائق مضت',
      hoursAgo: 'ساعات مضت',
      daysAgo: 'أيام مضت',
      noClassesAssigned: 'لا توجد فصول مخصصة لك',
      noClassesFound: 'لم يتم العثور على فصول',
      examGrades: 'نتائج الاختبارات',

      // ==================== ADDITIONAL KEYS ====================
      clickRegisterToAddChild: 'انقر "تسجيل طفل" لإضافة طفلك الأول',
      studentId: 'رقم الطالب',
      viewAllLeads: 'عرض جميع العملاء',
      viewAllPending: 'عرض جميع المعلقات',
      reviewPayment: 'مراجعة الدفع',
      paymentsAwaitingYourApproval: 'مدفوعات في انتظار موافقتك',
      allPaymentsHaveBeenProcessed: 'تمت معالجة جميع المدفوعات',
      reviewAndApprove: 'مراجعة والموافقة',
      convertAndRegister: 'تحويل وتسجيل',
      selectChildToViewAttendance: 'اختر طفلاً لعرض الحضور',
      selectChildToViewGrades: 'اختر طفلاً لعرض الدرجات',
      childNotFound: 'الطفل غير موجود',
      registerChildToGetStarted: 'سجل طفلاً للبدء',
      upcomingExams: 'الامتحانات القادمة',
      todayAttendance: 'حضور اليوم',

      // Navigation & Footer
      home: 'الرئيسية',
      about: 'عن المدرسة',
      programs: 'البرامج',
      admissions: 'القبول',
      contact: 'اتصل بنا',
      footerAboutText: 'توفير تعليم عالي الجودة لقادة المستقبل منذ عام 2000. نحن ملتزمون بالتميز في التعليم والتعلم.',
      quickLinks: 'روابط سريعة',
      workingHours: 'ساعات العمل',
      sundayToThursday: 'الأحد - الخميس',
      friday: 'الجمعة',
      closed: 'مغلق',
      saturday: 'السبت',
      allRightsReserved: 'جميع الحقوق محفوظة',

      // Schedule
      previousWeek: 'الأسبوع السابق',
      nextWeek: 'الأسبوع التالي',
      time: 'الوقت',
      teacher: 'المعلم',
      room: 'القاعة',
      legend: 'الإرشادات',
      regularClass: 'حصة عادية',
      exam: 'امتحان',
      activity: 'نشاط',
      holiday: 'عطلة',
      noSchedule: 'لا توجد حصص م scheduled لهذا اليوم',

      // Dashboard Stats
      totalStudents: 'إجمالي الطلاب',
      totalTeachers: 'إجمالي المعلمين',
      pendingParents: 'أولياء أمور معلقين',
      pendingStudents: 'طلاب معلقين',
      newLeads: 'عملاء جدد',
      conversionRate: 'نسبة التحويل',

      // Messages
      confirmDelete: 'هل أنت متأكد من الحذف؟',
      operationSuccessful: 'تمت العملية بنجاح',
      operationFailed: 'فشلت العملية',
      networkError: 'خطأ في الشبكة. يرجى التحقق من الاتصال',
      tryAgain: 'حاول مرة أخرى',
      submitting: 'جاري الإرسال...'
    }
  }

  const t = (key) => {
    const translation = translations[currentLocale.value][key]
    return translation || key
  }

  const setLocale = (locale) => {
    currentLocale.value = locale
    localStorage.setItem('locale', locale)
    document.documentElement.dir = locale === 'ar' ? 'rtl' : 'ltr'
    document.documentElement.lang = locale
  }

  const isRTL = computed(() => currentLocale.value === 'ar')

  return {
    currentLocale,
    t,
    setLocale,
    isRTL
  }
})