import { defineStore } from 'pinia'
import { ref, computed } from 'vue'

export const useLanguageStore = defineStore('language', () => {
  const currentLocale = ref(localStorage.getItem('locale') || 'en')
  
  const translations = {
    en: {
      // Common
      dashboard: 'Dashboard',
      students: 'Students',
      teachers: 'Teachers',
      classes: 'Classes',
      attendance: 'Attendance',
      payments: 'Payments',
      crm: 'CRM',
      reports: 'Reports',
      settings: 'Settings',
      logout: 'Logout',
      login: 'Login',
      register: 'Register',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      add: 'Add',
      search: 'Search',
      filter: 'Filter',
      actions: 'Actions',
      status: 'Status',
      date: 'Date',
      description: 'Description',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      confirm: 'Confirm',
      yes: 'Yes',
      no: 'No',
      back: 'Back',
      next: 'Next',
      previous: 'Previous',
      submit: 'Submit',
      update: 'Update',
      create: 'Create',
      view: 'View',
      total: 'Total',
      active: 'Active',
      inactive: 'Inactive',
      pending: 'Pending',
      approved: 'Approved',
      rejected: 'Rejected',
      cancelled: 'Cancelled',
      select: 'Select',
      
      // School Name
      schoolName: 'Zack International Schools and Kindergarten',
      tagline: 'Where Excellence Meets Values',
      
      // Parent Dashboard
      parentDashboard: 'Parent Dashboard',
      myChildren: 'My Children',
      registerChild: 'Register Child',
      childRegistrationNote: 'Your child will be registered after admin approval. You will be notified once approved.',
      submitForApproval: 'Submit for Approval',
      childRegistrationSubmitted: 'Child registration submitted for admin approval! You will be notified once approved.',
      parentNotFound: 'Parent profile not found. Please contact school administration.',
      parentNotApproved: 'Your account is not yet approved. Please contact the school administrator.',
      parentNoSchool: 'No school assigned to your account. Please contact the school administrator.',
      pendingApprovalMessage: 'Your account is pending approval from the school administrator. Once approved, you will be able to register children and access all features.',
      contactSchoolAdminForActivation: 'Please contact the school administrator to activate your account.',
      awaitingApproval: 'Awaiting Admin Approval',
      noChildren: 'No children found',
      viewDetails: 'View Details',
      childDetails: 'Child Details',
      childrenAttendance: 'Children Attendance',
      
      // Admin Dashboard - Pending Approvals
      pendingParentRegistrations: 'Pending Parent Registrations',
      reviewAndApproveParents: 'Review and approve parent registrations',
      approveParentRegistration: 'Approve Parent Registration',
      approveParent: 'Approve Parent',
      approveParentNote: 'This parent will be linked to your school and will be able to register children and view their progress.',
      relationship: 'Relationship',
      father: 'Father',
      mother: 'Mother',
      guardian: 'Guardian',
      pendingStudentRegistrations: 'Pending Student Registrations',
      reviewStudentRegistrations: 'Review and approve student registrations',
      approveStudentRegistration: 'Approve Student Registration',
      approveAndRegister: 'Approve & Register',
      studentNumberHelp: 'Unique identifier for the student',
      processing: 'Processing...',
      exportReport: 'Export Report',
      thisMonth: 'this month',
      today: 'Today',
      due: 'due',
      activeStaff: 'active staff',
      latestSchoolActivities: 'Latest school activities',
      noRecentActivity: 'No recent activity',
      attendanceTrend: 'Attendance Trend',
      revenueOverview: 'Revenue Overview',
      generateAndExportReports: 'Generate and export reports',
      performanceReportDesc: 'View student performance across subjects',
      attendanceReportDesc: 'View attendance statistics by class',
      revenueReportDesc: 'View revenue and payment statistics',
      pendingPaymentsReportDesc: 'View all pending payments',
      viewAndExportAttendance: 'View and export attendance records',
      tryDifferentFilters: 'Try different filters',
      noAttendanceRecords: 'No attendance records found',
      
      // Teacher related
      teacherName: 'Teacher Name',
      teacherCode: 'Teacher Code',
      qualification: 'Qualification',
      specialization: 'Specialization',
      hireDate: 'Hire Date',
      onLeave: 'On Leave',
      subjects: 'Subjects',
      notAssigned: 'Not Assigned',
      editTeacher: 'Edit Teacher',
      addTeacher: 'Add Teacher',
      editTeacherDescription: 'Update teacher information and account details',
      addTeacherDescription: 'Create a new teacher account and profile',
      basicInformation: 'Basic Information',
      contactInformation: 'Contact Information',
      professionalInformation: 'Professional Information',
      employmentInformation: 'Employment Information',
      enterFullName: 'Enter full name',
      enterArabicName: 'Enter name in Arabic',
      enterEmail: 'Enter email address',
      enterPhone: 'Enter phone number',
      enterQualification: 'Enter qualification (e.g., Bachelor of Education)',
      enterSpecialization: 'Enter specialization (e.g., Mathematics)',
      enterPassword: 'Enter password',
      teacherAccount: 'Teacher Account',
      teacherAccountHelp: 'Create login credentials for the teacher to access the system',
      saveTeacher: 'Save Teacher',
      accountCredentialsRequired: 'Email and password are required to create a teacher account',
      errorOccurred: 'An error occurred. Please try again.',
      addSubject: 'Add Subject',
      addSubjectPlaceholder: 'Add subject (e.g., Mathematics)',
      noSubjectsAdded: 'No subjects added. Click "Add Subject" to add.',
      passwordTooShort: 'Password must be at least 6 characters',
      
      // Student related
      studentName: 'Student Name',
      studentNumber: 'Student Number',
      dateOfBirth: 'Date of Birth',
      gender: 'Gender',
      male: 'Male',
      female: 'Female',
      enrollmentDate: 'Enrollment Date',
      class: 'Class',
      parent: 'Parent',
      contactInfo: 'Contact Information',
      address: 'Address',
      phone: 'Phone',
      email: 'Email',
      fullName: 'Full Name',
      arabicName: 'Name in Arabic',
      nationality: 'Nationality',
      religion: 'Religion',
      emergencyContact: 'Emergency Contact',
      medicalInfo: 'Medical Information',
      graduated: 'Graduated',
      transferred: 'Transferred',
      suspended: 'Suspended',
      editStudent: 'Edit Student',
      addStudent: 'Add Student',
      studentAccount: 'Student Account',
      studentAccountHelp: 'Create a login account for the student to access the student portal',
      createStudentAccount: 'Create Student Account',
      linkExistingUser: 'Link to existing user',
      createNewAccount: 'Create new account',
      selectUser: 'Select User',
      noAccount: 'No account (student will not have portal access)',
      personalInformation: 'Personal Information',
      academicInformation: 'Academic Information',
      parentName: 'Parent Name',
      parentPhone: 'Parent Phone',
      manualStudentRequired: 'Please enter at least student name and number',
      
      // Class related
      className: 'Class Name',
      gradeLevel: 'Grade Level',
      section: 'Section',
      academicYear: 'Academic Year',
      capacity: 'Capacity',
      currentEnrollment: 'Current Enrollment',
      selectClass: 'Select Class',
      selectTeacher: 'Select Teacher',
      allClasses: 'All Classes',
      noStudentsInClass: 'No students in this class',
      
      // Attendance
      present: 'Present',
      absent: 'Absent',
      late: 'Late',
      excused: 'Excused',
      attendanceReport: 'Attendance Report',
      startDate: 'Start Date',
      endDate: 'End Date',
      generateReport: 'Generate Report',
      attendanceRate: 'Attendance Rate',
      saving: 'Saving...',
      checkIn: 'Check In',
      checkOut: 'Check Out',
      attendanceRecord: 'Attendance Record',
      recentAttendance: 'Recent Attendance',
      noAttendance: 'No attendance records found',
      markedBy: 'Marked By',
      
      // Payment related
      amount: 'Amount',
      paymentMethod: 'Payment Method',
      bankak: 'Bankak',
      cash: 'Cash',
      dueDate: 'Due Date',
      paymentDate: 'Payment Date',
      transactionId: 'Transaction ID',
      proofImage: 'Proof Image',
      approve: 'Approve',
      reject: 'Reject',
      paymentNumber: 'Payment Number',
      paymentType: 'Payment Type',
      tuition: 'Tuition',
      examFees: 'Exam Fees',
      activityFees: 'Activity Fees',
      other: 'Other',
      bankakNumber: 'Bankak Number',
      currentFile: 'Current file',
      view: 'View',
      paymentApproval: 'Payment Approval',
      noPendingPayments: 'No pending payments',
      addPayment: 'Add Payment',
      selectStudent: 'Select Student',
      reviewAndApprovePayments: 'Review and approve pending payments',
      viewProof: 'View Proof',
      approveError: 'Error approving payment. Please try again.',
      rejectError: 'Error rejecting payment. Please try again.',
      
      // Payment Form
      selectFromList: 'Select from List',
      manualEntry: 'Manual Entry',
      searchStudentsByNameClassPhone: 'Search students by name, class, or phone...',
      noStudentsFound: 'No students found',
      change: 'Change',
      manualEntryNote: 'Student will be created automatically when you save the payment.',
      schoolInformation: 'School Information',
      school: 'School',
      noSchoolAssigned: 'No school assigned',
      schoolInfoHelp: 'Teachers will be automatically assigned to your school',
      noSchoolAssignedError: 'You are not assigned to any school. Please contact the super administrator.',
      validAmountRequired: 'Please enter a valid amount',
      pleaseSelectStudent: 'Please select a student',
      
      // File Uploader
      clickOrDrag: 'Click or drag file to upload',
      acceptedFileTypes: 'Accepted file types:',
      uploaded: 'uploaded',
      
      // Student Dashboard
      studentDashboard: 'Student Dashboard',
      myProfile: 'My Profile',
      studentProfile: 'Student Profile',
      averageGrade: 'Average Grade',
      recentGrades: 'Recent Grades',
      noGrades: 'No grades available',
      studentPayments: 'My Payments',
      schedule: 'Schedule',
      studentSchedule: 'Class Schedule',
      overallAverage: 'Overall Average',
      bestSubject: 'Best Subject',
      needsImprovement: 'Needs Improvement',
      totalExams: 'Total Exams',
      gradesBySubject: 'Grades by Subject',
      detailedGrades: 'Detailed Grades',
      maxScore: 'Max Score',
      proof: 'Proof',
      viewProof: 'View Payment Proof',
      
      // CRM
      leads: 'Leads',
      leadStatus: 'Lead Status',
      new: 'New',
      contacted: 'Contacted',
      enrolled: 'Enrolled',
      lost: 'Lost',
      archived: 'Archived',
      followUp: 'Follow Up',
      source: 'Source',
      interestedProgram: 'Interested Program',
      studentGrade: 'Student Grade',
      addLead: 'Add Lead',
      pipeline: 'Pipeline',
      noLeads: 'No leads',
      convertToStudent: 'Convert to Student',
      convertLeadToParent: 'Convert this lead to a parent account?',
      leadDetails: 'Lead Details',
      inquiryForm: 'Inquiry Form',
      inquirySubmitted: 'Your inquiry has been submitted! We will contact you soon.',
      inquiryFailed: 'Failed to submit inquiry. Please try again.',
      submitInquiry: 'Submit Inquiry',
      existingAccountNote: 'If you already have an account, please login or register as a parent.',
      
      // Reports
      performanceReport: 'Performance Report',
      revenueReport: 'Revenue Report',
      pendingPaymentsReport: 'Pending Payments Report',
      export: 'Export',
      generate: 'Generate',
      
      // Super Admin
      superAdminDashboard: 'Super Admin Dashboard',
      totalSchools: 'Total Schools',
      totalUsers: 'Total Users',
      totalRevenue: 'Total Revenue',
      recentSchools: 'Recent Schools',
      createdAt: 'Created At',
      addSchool: 'Add School',
      slug: 'Slug',
      slugHelp: 'URL-friendly identifier (e.g., elite-school)',
      subscriptionPlan: 'Subscription Plan',
      subscriptionEndDate: 'Subscription End Date',
      statistics: 'Statistics',
      userManagement: 'User Management',
      searchUsers: 'Search users...',
      allRoles: 'All Roles',
      activate: 'Activate',
      deactivate: 'Deactivate',
      globalAnalytics: 'Global Analytics',
      revenueOverTime: 'Revenue Over Time',
      schoolGrowth: 'School Growth',
      topSchools: 'Top Schools',
      studentsCount: 'Students Count',
      teachersCount: 'Teachers Count',
      createSuperAdmin: 'Create Super Admin',
      superAdminWarning: 'Warning: Super admins have full access to all schools and data. Use with caution.',
      creating: 'Creating...',
      superAdminCreated: 'Super admin created successfully!',
      
      // Public Website
      enrollNow: 'Enroll Now',
      whyChooseUs: 'Why Choose Us',
      qualityEducation: 'Quality Education',
      qualityEducationDesc: 'Comprehensive curriculum designed for academic excellence',
      expertTeachers: 'Expert Teachers',
      expertTeachersDesc: 'Highly qualified and experienced teaching staff',
      modernFacilities: 'Modern Facilities',
      modernFacilitiesDesc: 'State-of-the-art classrooms and laboratories',
      ourMission: 'Our Mission',
      ourVision: 'Our Vision',
      missionText: 'To provide exceptional education that nurtures intellectual curiosity, critical thinking, and character development.',
      visionText: 'To be a leading educational institution that prepares students to excel in a rapidly changing world.',
      primarySchool: 'Primary School',
      middleSchool: 'Middle School',
      highSchool: 'High School',
      primaryDesc: 'Building strong foundations in core subjects with engaging activities',
      middleDesc: 'Developing critical thinking and subject specialization',
      highDesc: 'Advanced preparation for university and careers',
      coreSubjects: 'Core subjects (Math, Science, Languages)',
      activityBased: 'Activity-based learning',
      subjectSpecialization: 'Subject specialization options',
      careerGuidance: 'Career guidance',
      advancedSubjects: 'Advanced placement courses',
      collegePrep: 'College preparation',
      selectGrade: 'Select grade',
      message: 'Message',
      submitApplication: 'Submit Application',
      applicationSubmitted: 'Application submitted successfully! We will contact you soon.',
      getInTouch: 'Get in Touch',
      sendMessage: 'Send a Message',
      messageSent: 'Message sent successfully!',
      admissionsNote: 'Fill out this form and our admissions team will contact you soon.',
      learnMore: 'Learn More',
      whyChooseUsDesc: 'Discover what makes Zack International Schools the perfect choice for your child\'s education',
      ourPrograms: 'Our Programs',
      ourProgramsDesc: 'Comprehensive educational programs designed for every stage of development',
      startYourJourney: 'Start Your Journey Today',
      startYourJourneyDesc: 'Join our community of learners and discover the joy of education at Zack International Schools',
      contactUsToday: 'Contact Us Today',
      grades: 'Grades',
      
      // Navigation
      home: 'Home',
      about: 'About',
      programs: 'Programs',
      admissions: 'Admissions',
      contact: 'Contact',
      
      // Auth additional
      createAccount: 'Create Account',
      confirmPassword: 'Confirm Password',
      passwordsDoNotMatch: 'Passwords do not match',
      alreadyHaveAccount: 'Already have an account? Sign in',
      resetPassword: 'Reset Password',
      resetInstructions: 'Enter your email address and we will send you a link to reset your password',
      sendResetLink: 'Send Reset Link',
      backToLogin: 'Back to login',
      resetEmailSent: 'Password reset email sent! Check your inbox.',
      parentRegistration: 'Parent Registration',
      parentRegistrationNote: 'This registration is for parents only. School staff accounts can only be created by the Super Admin.',
      pendingAdminApproval: 'Your account is pending admin approval. You will be notified once approved.',
      registrationFailed: 'Registration failed. Please try again.',
      registrationSuccess: 'Registration successful!',
      pleaseSelectSchool: 'Please select a school',
      welcomeBack: 'Welcome back',
      
      // Footer
      footerAboutText: 'Providing quality education for future leaders since 2000. We are committed to excellence in teaching and learning.',
      quickLinks: 'Quick Links',
      workingHours: 'Working Hours',
      sundayToThursday: 'Sunday - Thursday',
      friday: 'Friday',
      closed: 'Closed',
      saturday: 'Saturday',
      allRightsReserved: 'All rights reserved',
      
      // Messages
      noData: 'No data found',
      confirmDelete: 'Are you sure you want to delete this?',
      operationSuccessful: 'Operation completed successfully',
      operationFailed: 'Operation failed',
      networkError: 'Network error. Please check your connection',
      tryAgain: 'Try again',
      submitting: 'Submitting...',
      
      // Dashboard stats
      totalStudents: 'Total Students',
      totalTeachers: 'Total Teachers',
      attendanceRate: 'Attendance Rate',
      revenue: 'Revenue',
      pendingPayments: 'Pending Payments',
      newLeads: 'New Leads',
      conversionRate: 'Conversion Rate',
      
      // Schedule related
      schedule: 'Schedule',
      previousWeek: 'Previous Week',
      nextWeek: 'Next Week',
      time: 'Time',
      teacher: 'Teacher',
      room: 'Room',
      legend: 'Legend',
      regularClass: 'Regular Class',
      exam: 'Exam',
      activity: 'Activity',
      holiday: 'Holiday',
      selectChild: 'Select Child',
      selectChildToViewAttendance: 'Select a child to view attendance',
      selectChildToViewGrades: 'Select a child to view grades',
      noSchedule: 'No classes scheduled for this day',
      childNotFound: 'Child not found'
    },
    ar: {
      // Common
      dashboard: 'لوحة التحكم',
      students: 'الطلاب',
      teachers: 'المعلمين',
      classes: 'الفصول',
      attendance: 'الحضور',
      payments: 'المدفوعات',
      crm: 'إدارة علاقات العملاء',
      reports: 'التقارير',
      settings: 'الإعدادات',
      logout: 'تسجيل خروج',
      login: 'تسجيل دخول',
      register: 'تسجيل',
      save: 'حفظ',
      cancel: 'إلغاء',
      delete: 'حذف',
      edit: 'تعديل',
      add: 'إضافة',
      search: 'بحث',
      filter: 'تصفية',
      actions: 'إجراءات',
      status: 'الحالة',
      date: 'التاريخ',
      description: 'الوصف',
      loading: 'جاري التحميل...',
      error: 'خطأ',
      success: 'نجاح',
      confirm: 'تأكيد',
      yes: 'نعم',
      no: 'لا',
      back: 'رجوع',
      next: 'التالي',
      previous: 'السابق',
      submit: 'إرسال',
      update: 'تحديث',
      create: 'إنشاء',
      view: 'عرض',
      total: 'الإجمالي',
      active: 'نشط',
      inactive: 'غير نشط',
      pending: 'قيد الانتظار',
      approved: 'موافق',
      rejected: 'مرفوض',
      cancelled: 'ملغي',
      select: 'اختر',
      
      // School Name
      schoolName: 'رياض ومدارس زاك العالمية',
      tagline: 'حيث تلتقي التميز بالقيم',
      
      // Parent Dashboard
      parentDashboard: 'لوحة تحكم ولي الأمر',
      myChildren: 'أطفالي',
      registerChild: 'تسجيل طفل',
      childRegistrationNote: 'سيتم تسجيل طفلك بعد موافقة المسؤول. سيتم إعلامك بمجرد الموافقة.',
      submitForApproval: 'إرسال للموافقة',
      childRegistrationSubmitted: 'تم إرسال تسجيل الطفل للموافقة! سيتم إعلامك بمجرد الموافقة.',
      parentNotFound: 'لم يتم العثور على ملف ولي الأمر. يرجى الاتصال بإدارة المدرسة.',
      parentNotApproved: 'حسابك لم تتم الموافقة عليه بعد. يرجى الاتصال بمسؤول المدرسة.',
      parentNoSchool: 'لا توجد مدرسة مرتبطة بحسابك. يرجى الاتصال بمسؤول المدرسة.',
      pendingApprovalMessage: 'حسابك قيد موافقة مسؤول المدرسة. بمجرد الموافقة، ستتمكن من تسجيل الأطفال والوصول إلى جميع الميزات.',
      contactSchoolAdminForActivation: 'يرجى الاتصال بمسؤول المدرسة لتفعيل حسابك.',
      awaitingApproval: 'في انتظار موافقة المسؤول',
      noChildren: 'لا يوجد أطفال',
      viewDetails: 'عرض التفاصيل',
      childDetails: 'تفاصيل الطفل',
      childrenAttendance: 'حضور الأطفال',
      
      // Admin Dashboard - Pending Approvals
      pendingParentRegistrations: 'تسجيلات أولياء الأمور المعلقة',
      reviewAndApproveParents: 'مراجعة والموافقة على تسجيلات أولياء الأمور',
      approveParentRegistration: 'الموافقة على تسجيل ولي الأمر',
      approveParent: 'الموافقة على ولي الأمر',
      approveParentNote: 'سيتم ربط ولي الأمر بمدرستك وسيتمكن من تسجيل الأطفال ومتابعة تقدمهم.',
      relationship: 'صلة القرابة',
      father: 'أب',
      mother: 'أم',
      guardian: 'وصي',
      pendingStudentRegistrations: 'تسجيلات الطلاب المعلقة',
      reviewStudentRegistrations: 'مراجعة والموافقة على تسجيلات الطلاب',
      approveStudentRegistration: 'الموافقة على تسجيل الطالب',
      approveAndRegister: 'موافقة وتسجيل',
      studentNumberHelp: 'معرف فريد للطالب',
      processing: 'جاري المعالجة...',
      exportReport: 'تصدير التقرير',
      thisMonth: 'هذا الشهر',
      today: 'اليوم',
      due: 'مستحق',
      activeStaff: 'موظفين نشطين',
      latestSchoolActivities: 'أحدث الأنشطة المدرسية',
      noRecentActivity: 'لا يوجد نشاط حديث',
      attendanceTrend: 'اتجاه الحضور',
      revenueOverview: 'نظرة عامة على الإيرادات',
      generateAndExportReports: 'إنشاء وتصدير التقارير',
      performanceReportDesc: 'عرض أداء الطلاب في المواد المختلفة',
      attendanceReportDesc: 'عرض إحصائيات الحضور حسب الفصل',
      revenueReportDesc: 'عرض إحصائيات الإيرادات والمدفوعات',
      pendingPaymentsReportDesc: 'عرض جميع المدفوعات المعلقة',
      viewAndExportAttendance: 'عرض وتصدير سجلات الحضور',
      tryDifferentFilters: 'جرب عوامل تصفية مختلفة',
      noAttendanceRecords: 'لا توجد سجلات حضور',
      
      // Teacher related
      teacherName: 'اسم المعلم',
      teacherCode: 'رمز المعلم',
      qualification: 'المؤهل',
      specialization: 'التخصص',
      hireDate: 'تاريخ التوظيف',
      onLeave: 'في إجازة',
      subjects: 'المواد',
      notAssigned: 'غير معين',
      editTeacher: 'تعديل المعلم',
      addTeacher: 'إضافة معلم',
      editTeacherDescription: 'تحديث معلومات المعلم وتفاصيل الحساب',
      addTeacherDescription: 'إنشاء حساب معلم جديد وملف شخصي',
      basicInformation: 'المعلومات الأساسية',
      contactInformation: 'معلومات الاتصال',
      professionalInformation: 'المعلومات المهنية',
      employmentInformation: 'معلومات التوظيف',
      enterFullName: 'أدخل الاسم الكامل',
      enterArabicName: 'أدخل الاسم بالعربية',
      enterEmail: 'أدخل البريد الإلكتروني',
      enterPhone: 'أدخل رقم الهاتف',
      enterQualification: 'أدخل المؤهل (مثل: بكالوريوس تربية)',
      enterSpecialization: 'أدخل التخصص (مثل: رياضيات)',
      enterPassword: 'أدخل كلمة المرور',
      teacherAccount: 'حساب المعلم',
      teacherAccountHelp: 'إنشاء بيانات تسجيل دخول للمعلم للوصول إلى النظام',
      saveTeacher: 'حفظ المعلم',
      accountCredentialsRequired: 'البريد الإلكتروني وكلمة المرور مطلوبان لإنشاء حساب المعلم',
      errorOccurred: 'حدث خطأ. يرجى المحاولة مرة أخرى.',
      addSubject: 'إضافة مادة',
      addSubjectPlaceholder: 'أضف مادة (مثل: رياضيات)',
      noSubjectsAdded: 'لم يتم إضافة مواد. انقر "إضافة مادة" للإضافة.',
      passwordTooShort: 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل',
      
      // Student related
      studentName: 'اسم الطالب',
      studentNumber: 'رقم الطالب',
      dateOfBirth: 'تاريخ الميلاد',
      gender: 'الجنس',
      male: 'ذكر',
      female: 'أنثى',
      enrollmentDate: 'تاريخ التسجيل',
      class: 'الفصل',
      parent: 'ولي الأمر',
      contactInfo: 'معلومات الاتصال',
      address: 'العنوان',
      phone: 'الهاتف',
      email: 'البريد الإلكتروني',
      fullName: 'الاسم الكامل',
      arabicName: 'الاسم بالعربية',
      nationality: 'الجنسية',
      religion: 'الديانة',
      emergencyContact: 'جهة اتصال للطوارئ',
      medicalInfo: 'معلومات طبية',
      graduated: 'متخرج',
      transferred: 'منقول',
      suspended: 'موقوف',
      editStudent: 'تعديل الطالب',
      addStudent: 'إضافة طالب',
      studentAccount: 'حساب الطالب',
      studentAccountHelp: 'إنشاء حساب تسجيل دخول للطالب للوصول إلى بوابة الطالب',
      createStudentAccount: 'إنشاء حساب طالب',
      linkExistingUser: 'ربط بمستخدم موجود',
      createNewAccount: 'إنشاء حساب جديد',
      selectUser: 'اختر المستخدم',
      noAccount: 'لا يوجد حساب (لن يكون للطالب وصول إلى البوابة)',
      personalInformation: 'المعلومات الشخصية',
      academicInformation: 'المعلومات الأكاديمية',
      parentName: 'اسم ولي الأمر',
      parentPhone: 'هاتف ولي الأمر',
      manualStudentRequired: 'يرجى إدخال اسم الطالب ورقمه على الأقل',
      
      // Class related
      className: 'اسم الفصل',
      gradeLevel: 'الصف الدراسي',
      section: 'الشعبة',
      academicYear: 'السنة الدراسية',
      capacity: 'السعة',
      currentEnrollment: 'عدد المسجلين',
      selectClass: 'اختر الفصل',
      selectTeacher: 'اختر المعلم',
      allClasses: 'جميع الفصول',
      noStudentsInClass: 'لا يوجد طلاب في هذا الفصل',
      
      // Attendance
      present: 'حاضر',
      absent: 'غائب',
      late: 'متأخر',
      excused: 'معذور',
      attendanceReport: 'تقرير الحضور',
      startDate: 'تاريخ البداية',
      endDate: 'تاريخ النهاية',
      generateReport: 'إنشاء التقرير',
      attendanceRate: 'نسبة الحضور',
      saving: 'جاري الحفظ...',
      checkIn: 'وقت الدخول',
      checkOut: 'وقت الخروج',
      attendanceRecord: 'سجل الحضور',
      recentAttendance: 'الحضور الأخير',
      noAttendance: 'لا توجد سجلات حضور',
      markedBy: 'تم بواسطة',
      
      // Payment related
      amount: 'المبلغ',
      paymentMethod: 'طريقة الدفع',
      bankak: 'بنكك',
      cash: 'نقدي',
      dueDate: 'تاريخ الاستحقاق',
      paymentDate: 'تاريخ الدفع',
      transactionId: 'رقم المعاملة',
      proofImage: 'صورة الإثبات',
      approve: 'موافقة',
      reject: 'رفض',
      paymentNumber: 'رقم الدفع',
      paymentType: 'نوع الدفع',
      tuition: 'رسوم دراسية',
      examFees: 'رسوم امتحانات',
      activityFees: 'رسوم أنشطة',
      other: 'أخرى',
      bankakNumber: 'رقم بنكك',
      currentFile: 'الملف الحالي',
      view: 'عرض',
      paymentApproval: 'الموافقة على الدفعات',
      noPendingPayments: 'لا توجد دفعات معلقة',
      addPayment: 'إضافة دفعة',
      selectStudent: 'اختر الطالب',
      reviewAndApprovePayments: 'مراجعة والموافقة على المدفوعات المعلقة',
      viewProof: 'عرض الإثبات',
      approveError: 'حدث خطأ أثناء الموافقة على الدفع. يرجى المحاولة مرة أخرى.',
      rejectError: 'حدث خطأ أثناء رفض الدفع. يرجى المحاولة مرة أخرى.',
      
      // Payment Form
      selectFromList: 'اختر من القائمة',
      manualEntry: 'إدخال يدوي',
      searchStudentsByNameClassPhone: 'بحث عن طالب بالاسم، الفصل، أو الهاتف...',
      noStudentsFound: 'لا يوجد طلاب',
      change: 'تغيير',
      manualEntryNote: 'سيتم إنشاء الطالب تلقائياً عند حفظ الدفعة.',
      schoolInformation: 'معلومات المدرسة',
      school: 'المدرسة',
      noSchoolAssigned: 'لا توجد مدرسة مرتبطة',
      schoolInfoHelp: 'سيتم تعيين المعلمين تلقائيًا إلى مدرستك',
      noSchoolAssignedError: 'أنت غير مرتبط بأي مدرسة. يرجى الاتصال بالمشرف العام.',
      validAmountRequired: 'يرجى إدخال مبلغ صحيح',
      pleaseSelectStudent: 'يرجى اختيار الطالب',
      
      // File Uploader
      clickOrDrag: 'انقر أو اسحب الملف للتحميل',
      acceptedFileTypes: 'أنواع الملفات المقبولة:',
      uploaded: 'تم التحميل',
      
      // Student Dashboard
      studentDashboard: 'لوحة تحكم الطالب',
      myProfile: 'ملفي الشخصي',
      studentProfile: 'الملف الشخصي للطالب',
      averageGrade: 'متوسط الدرجات',
      recentGrades: 'الدرجات الأخيرة',
      noGrades: 'لا توجد درجات متاحة',
      studentPayments: 'مدفوعاتي',
      schedule: 'الجدول الدراسي',
      studentSchedule: 'الجدول الدراسي',
      overallAverage: 'المعدل العام',
      bestSubject: 'أفضل مادة',
      needsImprovement: 'يحتاج تحسين',
      totalExams: 'إجمالي الامتحانات',
      gradesBySubject: 'الدرجات حسب المادة',
      detailedGrades: 'الدرجات التفصيلية',
      maxScore: 'الدرجة القصوى',
      proof: 'إثبات',
      viewProof: 'عرض إثبات الدفع',
      
      // CRM
      leads: 'العملاء المتوقعين',
      leadStatus: 'حالة العميل',
      new: 'جديد',
      contacted: 'تم التواصل',
      enrolled: 'مسجل',
      lost: 'مفقود',
      archived: 'مؤرشف',
      followUp: 'متابعة',
      source: 'المصدر',
      interestedProgram: 'البرنامج المهتم به',
      studentGrade: 'صف الطالب',
      addLead: 'إضافة عميل متوقع',
      pipeline: 'مسار المبيعات',
      noLeads: 'لا توجد عملاء',
      convertToStudent: 'تحويل إلى طالب',
      convertLeadToParent: 'تحويل هذا العميل إلى حساب ولي أمر؟',
      leadDetails: 'تفاصيل العميل',
      inquiryForm: 'نموذج الاستفسار',
      inquirySubmitted: 'تم إرسال استفسارك! سنتواصل معك قريباً.',
      inquiryFailed: 'فشل إرسال الاستفسار. يرجى المحاولة مرة أخرى.',
      submitInquiry: 'إرسال استفسار',
      existingAccountNote: 'إذا كان لديك حساب بالفعل، يرجى تسجيل الدخول أو التسجيل كولي أمر.',
      
      // Reports
      performanceReport: 'تقرير الأداء',
      revenueReport: 'تقرير الإيرادات',
      pendingPaymentsReport: 'تقرير المدفوعات المعلقة',
      export: 'تصدير',
      generate: 'إنشاء',
      
      // Super Admin
      superAdminDashboard: 'لوحة تحكم المشرف العام',
      totalSchools: 'إجمالي المدارس',
      totalUsers: 'إجمالي المستخدمين',
      totalRevenue: 'إجمالي الإيرادات',
      recentSchools: 'أحدث المدارس',
      createdAt: 'تاريخ الإنشاء',
      addSchool: 'إضافة مدرسة',
      slug: 'المعرف',
      slugHelp: 'معرف URL (مثال: elite-school)',
      subscriptionPlan: 'الباقة',
      subscriptionEndDate: 'تاريخ انتهاء الباقة',
      statistics: 'إحصائيات',
      userManagement: 'إدارة المستخدمين',
      searchUsers: 'بحث عن مستخدمين...',
      allRoles: 'جميع الأدوار',
      activate: 'تفعيل',
      deactivate: 'تعطيل',
      globalAnalytics: 'تحليلات عامة',
      revenueOverTime: 'الإيرادات عبر الوقت',
      schoolGrowth: 'نمو المدارس',
      topSchools: 'أفضل المدارس',
      studentsCount: 'عدد الطلاب',
      teachersCount: 'عدد المعلمين',
      createSuperAdmin: 'إنشاء مشرف عام',
      superAdminWarning: 'تحذير: المشرف العام لديه صلاحية الوصول الكامل لجميع المدارس والبيانات. استخدم بحذر.',
      creating: 'جاري الإنشاء...',
      superAdminCreated: 'تم إنشاء المشرف العام بنجاح!',
      
      // Public Website
      enrollNow: 'سجل الآن',
      whyChooseUs: 'لماذا نحن',
      qualityEducation: 'تعليم متميز',
      qualityEducationDesc: 'منهج دراسي شامل مصمم للتميز الأكاديمي',
      expertTeachers: 'معلمون خبراء',
      expertTeachersDesc: 'كادر تدريسي مؤهل وذو خبرة عالية',
      modernFacilities: 'مرافق حديثة',
      modernFacilitiesDesc: 'فصول دراسية ومعامل متطورة',
      ourMission: 'رسالتنا',
      ourVision: 'رؤيتنا',
      missionText: 'تقديم تعليم استثنائي ينمي الفضول الفكري والتفكير النقدي وتنمية الشخصية.',
      visionText: 'أن نكون مؤسسة تعليمية رائدة تعد الطلاب للتفوق في عالم سريع التغير.',
      primarySchool: 'المرحلة الابتدائية',
      middleSchool: 'المرحلة المتوسطة',
      highSchool: 'المرحلة الثانوية',
      primaryDesc: 'بناء أساس قوي في المواد الأساسية مع أنشطة تفاعلية',
      middleDesc: 'تطوير التفكير النقدي والتخصص في المواد',
      highDesc: 'إعداد متقدم للجامعة والحياة المهنية',
      coreSubjects: 'المواد الأساسية (رياضيات، علوم، لغات)',
      activityBased: 'تعلم قائم على الأنشطة',
      subjectSpecialization: 'خيارات التخصص في المواد',
      careerGuidance: 'توجيه مهني',
      advancedSubjects: 'مواد متقدمة',
      collegePrep: 'التحضير للجامعة',
      selectGrade: 'اختر الصف',
      message: 'الرسالة',
      submitApplication: 'تقديم الطلب',
      applicationSubmitted: 'تم تقديم الطلب بنجاح! سنتواصل معك قريباً.',
      getInTouch: 'تواصل معنا',
      sendMessage: 'أرسل رسالة',
      messageSent: 'تم إرسال الرسالة بنجاح!',
      admissionsNote: 'املأ هذا النموذج وسيتواصل معك فريق القبول قريباً.',
      learnMore: 'اعرف المزيد',
      whyChooseUsDesc: 'اكتشف ما يجعل مدارس زاك العالمية الخيار الأمثل لتعليم طفلك',
      ourPrograms: 'برامجنا',
      ourProgramsDesc: 'برامج تعليمية شاملة مصممة لكل مرحلة من مراحل التطور',
      startYourJourney: 'ابدأ رحلتك اليوم',
      startYourJourneyDesc: 'انضم إلى مجتمعنا التعليمي واكتشف متعة التعلم في مدارس زاك العالمية',
      contactUsToday: 'اتصل بنا اليوم',
      grades: 'الصفوف',
      
      // Navigation
      home: 'الرئيسية',
      about: 'عن المدرسة',
      programs: 'البرامج',
      admissions: 'القبول',
      contact: 'اتصل بنا',
      
      // Auth additional
      createAccount: 'إنشاء حساب',
      confirmPassword: 'تأكيد كلمة المرور',
      passwordsDoNotMatch: 'كلمات المرور غير متطابقة',
      alreadyHaveAccount: 'لديك حساب بالفعل؟ تسجيل الدخول',
      resetPassword: 'إعادة تعيين كلمة المرور',
      resetInstructions: 'أدخل بريدك الإلكتروني وسنرسل لك رابطاً لإعادة تعيين كلمة المرور',
      sendResetLink: 'إرسال رابط إعادة التعيين',
      backToLogin: 'العودة إلى تسجيل الدخول',
      resetEmailSent: 'تم إرسال بريد إعادة تعيين كلمة المرور! تحقق من صندوق الوارد.',
      parentRegistration: 'تسجيل ولي الأمر',
      parentRegistrationNote: 'هذا التسجيل مخصص لأولياء الأمور فقط. يمكن إنشاء حسابات موظفي المدرسة فقط بواسطة المشرف العام.',
      pendingAdminApproval: 'حسابك قيد موافقة المسؤول. سيتم إعلامك عند الموافقة.',
      registrationFailed: 'فشل التسجيل. يرجى المحاولة مرة أخرى.',
      registrationSuccess: 'تم التسجيل بنجاح!',
      pleaseSelectSchool: 'يرجى اختيار المدرسة',
      welcomeBack: 'مرحباً بعودتك',
      
      // Footer
      footerAboutText: 'توفير تعليم عالي الجودة لقادة المستقبل منذ عام 2000. نحن ملتزمون بالتميز في التعليم والتعلم.',
      quickLinks: 'روابط سريعة',
      workingHours: 'ساعات العمل',
      sundayToThursday: 'الأحد - الخميس',
      friday: 'الجمعة',
      closed: 'مغلق',
      saturday: 'السبت',
      allRightsReserved: 'جميع الحقوق محفوظة',
      
      // Messages
      noData: 'لا توجد بيانات',
      confirmDelete: 'هل أنت متأكد من الحذف؟',
      operationSuccessful: 'تمت العملية بنجاح',
      operationFailed: 'فشلت العملية',
      networkError: 'خطأ في الشبكة. يرجى التحقق من الاتصال',
      tryAgain: 'حاول مرة أخرى',
      submitting: 'جاري الإرسال...',
      
      // Dashboard stats
      totalStudents: 'إجمالي الطلاب',
      totalTeachers: 'إجمالي المعلمين',
      attendanceRate: 'نسبة الحضور',
      revenue: 'الإيرادات',
      pendingPayments: 'المدفوعات المعلقة',
      newLeads: 'عملاء جدد',
      conversionRate: 'نسبة التحويل',
      
      // Schedule related
      schedule: 'الجدول الدراسي',
      previousWeek: 'الأسبوع السابق',
      nextWeek: 'الأسبوع التالي',
      time: 'الوقت',
      teacher: 'المعلم',
      room: 'القاعة',
      legend: 'الإرشادات',
      regularClass: 'حصة عادية',
      exam: 'امتحان',
      activity: 'نشاط',
      holiday: 'عطلة',
      selectChild: 'اختر الطالب',
      selectChildToViewAttendance: 'اختر الطالب لعرض الحضور',
      selectChildToViewGrades: 'اختر الطالب لعرض الدرجات',
      noSchedule: 'لا توجد حصص م scheduled لهذا اليوم',
      childNotFound: 'الطالب غير موجود'
    }
  }
  
  const t = (key) => {
    const translation = translations[currentLocale.value][key]
    return translation || key
  }
  
  const setLocale = (locale) => {
    currentLocale.value = locale
    localStorage.setItem('locale', locale)
    document.documentElement.dir = locale === 'ar' ? 'rtl' : 'ltr'
    document.documentElement.lang = locale
  }
  
  const isRTL = computed(() => currentLocale.value === 'ar')
  
  return {
    currentLocale,
    t,
    setLocale,
    isRTL
  }
})